[workspace]
resolver = "2"

members = [
    "2023/day-1",
    "2023/day-2",
    "2023/day-3",
    "2023/day-4",
    "2023/day-5",
    "2023/day-6",
    "2023/day-7",
    "2023/day-8",
    "2023/day-9",
    "2023/day-10",
]